### ISSUE TITLE
While decrypting the file "AESDecryption.java"  I got some  IllegalBlockSizeException.

### ISSUE THREAD

**Issue by nikhil0269** [nikhil0269/FinalYearProjectG9#1]
javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:936)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at AES.decrypt(AES.java:74)
	at AESDecryption.main(AESDecryption.java:169)

**Comment by Shailender1911** [comment]
I have executed the code there are no such issues. It's working fine . can you recheck again?

**Comment by nikhil0269** [comment]
No , I am facing this issue every time when I run the code.
It's okay I will check it.
